export const freelanceJobs: string[] = [
        //Academic & Tutoring
        "Tutoring",
        "Homework Assistance",
        "Exam Preparation",
        "Language Lessons",
        "Proofreading & Editing",
        "Academic Research",
        "Note-Taking",
        "Study Guide Creation",
        "Thesis/Capstone Support",
        "Presentation Coaching",
        "Resume & Cover Letter Writing",
        "Grant & Scholarship Writing",
        "Transcription Services",
    
        // Technology & Digital
        "Web Development",
        "Mobile App Development",
        "Computer Repair",
        "Tech Support",
        "Software Installation",
        "Device Setup & Troubleshooting",
        "Data Entry",
        "Graphic Design",
        "Presentation Design",
        "Printing Services",
        "Photography & Photo Editing",
        "Video Editing",
        "Social Media Management",
        "SEO Assistance",
        "Podcast Production",
        "Blog Management",
        "Content Creation",
        "UX/UI Design",
        "Website Maintenance",
        "App Testing",
        "Cybersecurity Consultation",
        "Database Assistance",
        "Spreadsheet & Excel Assistance",
    
        // Creative & Writing
        "Creative Writing",
        "Blog Writing",
        "Script Writing",
        "Journalism",
        "Poetry Writing",
        "Technical Writing",
        "Book & Article Summarizing",
        "Illustration & Art",
        "Calligraphy & Hand Lettering",
        "Graphic Novels & Comics Creation",
        "Flyer & Poster Design",
        "Sticker & Merchandise Design",
    
        // Personal Care & Beauty
        "Barbering",
        "Hairstyling",
        "Hair Braiding",
        "Hair Coloring",
        "Makeup Services",
        "Fashion Styling",
        "Personal Shopping",
        "Tailoring & Clothing Alterations",
        "Nail Technician",
        "Manicure & Pedicure Services",
        "Eyelash Extensions",
        "Eyebrow Threading & Waxing",
        "Tattoo Design",
        "Henna Art",
        "Piercing Services",
        "Skincare Consulting",
    
        // Mechanical & Technical
        "Bike Repair & Maintenance",
        "Car Maintenance & Mechanic Work",
        "Electronics Repair",
        "Smartphone Repair",
        "Tablet & Laptop Repair",
        "Gaming Console Repair",
        "Appliance Repair",
        "Furniture Repair & Restoration",
        "Woodworking & Carpentry",
        "3D Printing Services",
    
        // Fitness & Health
        "Personal Training",
        "Yoga Instruction",
        "Fitness Coaching",
        "Nutrition Advice",
        "Meal Preparation",
        "Sports Coaching",
        "Dance Instruction",
        "Martial Arts Training",
        "Meditation & Mindfulness Coaching",
    
        // Event & Entertainment
        "Event Planning",
        "DJ Services",
        "Music Lessons",
        "Photography for Events",
        "Videography for Events",
        "Live Performance (Music/Dance)",
        "Event Decoration",
        "Party Hosting & Coordination",
        "Face Painting",
        "Magic & Entertainment",
        "MC/Hosting Services",
    
        // Lifestyle & Domestic Services
        "Pet Sitting & Dog Walking",
        "House Sitting",
        "Cleaning & Organization",
        "Laundry Services",
        "Moving Assistance",
        "Gardening & Plant Care",
        "Furniture Assembly",
        "Grocery & Errand Running",
        "Delivery Services",
        "Dorm Room Decorating",
        "Snack & Food Preparation",
        "Custom Gift-Making",
        "Gift Wrapping Services",
        "Personal Assistance & Errands",
        "Meal Delivery",
        "Plant-Based Cooking & Baking",
    
        // Social & Community Services
        "Community Management",
        "Volunteer Coordination",
        "Campus Tour Guiding",
        "Orientation Assistance",
        "Mentorship & Peer Support",
        "Crisis Counseling & Support (if qualified)",
    
        // Business & Administrative
        "Virtual Assistance",
        "Administrative Support",
        "Scheduling & Appointment Management",
        "Market Research & Surveys",
        "Sales & Promotion Assistance",
        "Customer Support",
        "Product Testing & Reviews",
        "Bookkeeping (basic)",
        "Inventory Management",
    
        // Crafts & Artistic Services
        "Custom Jewelry Making",
        "Handmade Crafts",
        "Pottery & Ceramics",
        "Candle & Soap Making",
        "T-shirt Printing",
        "Embroidery & Sewing",
        "Leatherworking",
        "Knitting & Crochet",
        "Art Commissions",
    
        // Travel & Transport
        "Ride Sharing & Carpooling",
        "Local Travel Planning",
        "Transportation & Shuttle Services",
        "Parking Spot Rental",
    
        // Gaming & Hobby Related
        "Gaming Coaching",
        "Board Game Event Hosting",
        "Esports & Tournament Organization",
        "Collectibles & Trading Services",
        "Cosplay Design & Creation",
    
        // Miscellaneous
        "Language Translation Services",
        "Interpretation Services",
        "Tarot Card & Fortune Telling",
        "Astrology Readings",
        "Interior Decorating Assistance",
        "Roommate Matching Services",
        "Campus Housing Advising"
    ]
    
